### ISSUE TITLE
Exercises doesn't work unfortunately

### ISSUE THREAD

**Issue by tgfjt** [finnp/test-anything#18]
Hi.
(when trying i18n support for test-anything.:smile: )
Unfortunately I select the exercise then get Error.:sob: 

```
/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/node_modules/cli-md/node_modules/marked/lib/marked.js:1226
    throw e;
          ^
TypeError: this.renderer.text is not a function
Please report this to https://github.com/chjj/marked.
    at InlineLexer.output (/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/node_modules/cli-md/node_modules/marked/lib/marked.js:685:28)
    at Parser.tok (/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/node_modules/cli-md/node_modules/marked/lib/marked.js:985:21)
    at Parser.parse (/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/node_modules/cli-md/node_modules/marked/lib/marked.js:935:17)
    at Function.Parser.parse (/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/node_modules/cli-md/node_modules/marked/lib/marked.js:922:17)
    at marked (/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/node_modules/cli-md/node_modules/marked/lib/marked.js:1218:19)
    at exports.parse (/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/exercises/utils/index.js:7:10)
    at Object.<anonymous> (/Users/tgfjt/.nodebrew/iojs/v2.3.4/lib/node_modules/test-anything/exercises/log-it-out/index.js:9:19)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
```

New version of marked is not good for marked-terminal.

ref: https://github.com/mikaelbr/marked-terminal/issues/18

**Comment by tgfjt** [comment]
Fixed with marked-terminal v1.6.0:tada:
